### ISSUE TITLE
Always show tab favicon in vertical tab bar

### ISSUE THREAD

**Issue by Keith94** [Croydon/vertical-tabs-reloaded#25]
It can be enabled using this css:

```css
.tabbrowser-tabs[orient="vertical"]
  .tabbrowser-tab:not([busy])
  .tab-icon-image:not([src]):not([pinned]) {
	display: -moz-box;
}
```
Comparison:

![ezgif-1247776065](https://cloud.githubusercontent.com/assets/5490615/14063213/a7969134-f37b-11e5-9d43-6754fe6ab045.gif)
