### ISSUE TITLE
[Dark theme] Use white images for close and sound buttons

### ISSUE THREAD

**Issue by Keith94** [Croydon/vertical-tabs-reloaded#26]
Example CSS:
```css
.tab-close-button {
  list-style-image: url("chrome://global/skin/icons/close-inverted.png") !important;
}
.tab-icon-sound[soundplaying] {
  list-style-image: url("chrome://browser/skin/tabbrowser/tab-audio.svg#tab-audio-white") !important;
}
.tab-icon-sound[muted] {
  list-style-image: url("chrome://browser/skin/tabbrowser/tab-audio.svg#tab-audio-muted-white") !important;
}
```

Comparison:
![darktheme](https://cloud.githubusercontent.com/assets/5490615/14063580/f3f181fe-f38c-11e5-9b03-c1312d380501.gif)

**Comment by Croydon** [comment]
There is a problem with the close icons. It looks like this:
![](https://cloud.githubusercontent.com/assets/1593194/14066030/e378176c-f43f-11e5-93a3-b342cb99472a.PNG)

Code:
https://github.com/Croydon/vertical-tabs-reloaded/blob/themes_white_icons/data/skin/dark/tab.css#L1

**Comment by Keith94** [comment]
Hmm, it's working as intended on my system (Windows 8, Firefox 48). Could yours be a high DPI issue? Does this css fix it?

```css
@media (min-resolution: 1.1dppx) {
  .tab-close-button {
    list-style-image: url("chrome://global/skin/icons/close-inverted@2x.png") !important;
  }
}
```
