### ISSUE TITLE
Close button shown trice with dark theme

### ISSUE THREAD

**Issue by alexander255** [Croydon/vertical-tabs-reloaded#35]
I tried to switch to the dark theme, but I think you're missing some image clipping with this theme:

![Screenshot](https://cloud.githubusercontent.com/assets/246386/14204734/85585bc2-f806-11e5-9ef9-8d259621fdae.png)

Vertical Tabs Reloaded 0.5.0
Firefox 46.0b2, Linux 4.4, x86_64

**Comment by yafp** [comment]
I can reproduce that with VTR 0.5.0 using the dark theme (FF 45 on Linux).

**Comment by Croydon** [comment]
I can confirm this as well on my Fedora machine, but not on my Windows setup.
Seems to be Linux only.

This is a follow up problem of #26. I'm wondering if @Keith94 would be willing to look into that once again? :smile:

**Comment by Keith94** [comment]
@Croydon Well I don't have a Linux environment to reproduce this in, so I'm not entirely sure how to fix it. I played around with `-moz-image-region` to get a specific image for the different attributes. Maybe it will work for the 100% DPI setting...

```css
.tab-close-button {
    -moz-image-region: rect(0px, 20px, 20px, 0px) !important;
}
.tab-close-button:hover {
    -moz-image-region: rect(0px, 40px, 20px, 20px) !important;
}
.tab-close-button:active {
    -moz-image-region: rect(0px, 60px, 20px, 40px) !important;
}
```
