### ISSUE TITLE
Window control buttons looks bad In Win10 then title bar is hidden

### ISSUE THREAD

**Issue by Cepr0** [Croydon/vertical-tabs-reloaded#64]
![2016-09-01_20-30-17](https://cloud.githubusercontent.com/assets/10778600/18177693/0fabc3d6-7084-11e6-8aaf-a4e6363cd203.gif)

Add-on version: 0.7.0
Firefox version: 48.0.2
OS + OS-Version: Win10
Other tab + user interface related add-ons:  TabMix Plus

**Comment by myBestSoftAndPref** [comment]
It happens because title bar is not hidden. It's just partially invisible.  
Hot fix for Stylish addon or userChrome.css:
```css
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

#titlebar
{
  display : none !important;
}
```
